### ISSUE TITLE
Missing emoji in BaseFont.IDENTITY_H encoding

### ISSUE THREAD

**Issue by amirmostaghim** [VahidN/iTextSharp.LGPLv2.Core#58]
# Summary of the issue

I search a lot of links in google but not found any valuable docs for it.

I want to export pdf file using ITextSharp library that contains Persian, English, Emoji and special

## Environment

```
iTextSharp.LGPLv2.Core version: 1.6.7
.NET Core SDK version: 3.1.101
IDE: vs 2019
```

## Example code/Steps to reproduce:

```
public PdfGenerator( BaseFont bf = null)
{
    _bf = bf ?? BaseFont.CreateFont(Environment.GetEnvironmentVariable("windir") + @"\fonts\iransans.ttf",
              BaseFont.IDENTITY_H, true);

}

var fontNormal = new Font(_bf, 12, Font.NORMAL, BaseColor.Black);

table.AddCell(new PdfPCell(new Phrase(12, text, fontNormal))
{
   RunDirection = PdfWriter.RUN_DIRECTION_RTL,
   BorderWidth = 0,
   Padding = 20,
   Colspan = isLongText ? 3 : 2,
   CellEvent = new RoundedBorder2()
});
```

**Comment by VahidN** [comment]
You font doesn't support a lot of different characters. you can open with `character map` application on Windows to see what's in it. So ... the final output won't have your special characters, because your font doesn't support them. iTextSharp has the `FontSelector` utility to support it. Add all of the required fonts which have all of your characters to it and then use it. [You can find a sample about it here in Persian](https://www.dotnettips.info/post/621/itextsharp-%d9%88-%d8%a7%d8%b3%d8%aa%d9%81%d8%a7%d8%af%d9%87-%d8%a7%d8%b2-%d9%82%d9%84%d9%85%e2%80%8c%d9%87%d8%a7%db%8c-%d9%85%d8%ad%d8%af%d9%88%d8%af-%d9%81%d8%a7%d8%b1%d8%b3%db%8c).
